---
deployment:
 tasks:
 - export DEPLOYPATH=/home/knounecom/public_html/
 - /bin/cp -r ./app $DEPLOYPATH
 - /bin/cp -r ./bootstrap $DEPLOYPATH
 - /bin/cp -r ./config $DEPLOYPATH
 - /bin/cp -r ./database $DEPLOYPATH
 - /bin/cp -r ./hooks $DEPLOYPATH
 - /bin/cp -r ./node_modules $DEPLOYPATH
 - /bin/cp -r ./public $DEPLOYPATH
 - /bin/cp -r ./ressources $DEPLOYPATH
 - /bin/cp -r ./routes $DEPLOYPATH
 - /bin/cp -r ./tests $DEPLOYPATH
 - /bin/cp -r ./vendor $DEPLOYPATH
 - /bin/cp .editorconfig $DEPLOYPATH
 - /bin/cp .env $DEPLOYPATH
 - /bin/cp composer.json $DEPLOYPATH
 - /bin/cp composer.lock $DEPLOYPATH
 - /bin/cp artisan $DEPLOYPATH
 - /bin/cp LICENSE $DEPLOYPATH
 - /bin/cp package.json $DEPLOYPATH
 - /bin/cp phpunit.xml $DEPLOYPATH
 - /bin/cp readme.md $DEPLOYPATH
 - /bin/cp server.php $DEPLOYPATH
 - /bin/cp webpack.mix.js $DEPLOYPATH