---
deployment:
 tasks:
 - export DEPLOYPATH=/home/knounecom/public_html/
 - /bin/cp app $DEPLOYPATH
 - /bin/cp bootstrap $DEPLOYPATH
 - /bin/cp config $DEPLOYPATH
 - /bin/cp database $DEPLOYPATH
 - /bin/cp hooks $DEPLOYPATH
 - /bin/cp node_modules $DEPLOYPATH
 - /bin/cp public $DEPLOYPATH
 - /bin/cp ressources $DEPLOYPATH
 - /bin/cp routes $DEPLOYPATH
 - /bin/cp tests $DEPLOYPATH
 - /bin/cp vendor $DEPLOYPATH
 - /bin/cp .editorconfig $DEPLOYPATH
 - /bin/cp .env $DEPLOYPATH
 - /bin/cp composer.json $DEPLOYPATH
 - /bin/cp composer.lock $DEPLOYPATH
 - /bin/cp artisan $DEPLOYPATH
 - /bin/cp LICENSE $DEPLOYPATH
 - /bin/cp package.json $DEPLOYPATH
 - /bin/cp phpunit.xml $DEPLOYPATH
 - /bin/cp readme.md $DEPLOYPATH
 - /bin/cp server.php $DEPLOYPATH
 - /bin/cp webpack.mix.js $DEPLOYPATH